name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10.0'

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Add Test dependencies
        run: julia -e 'using Pkg; Pkg.add("Test")'

      - name: Install Conda and Python packages
        run: |
          julia -e 'using Pkg; Pkg.add("Conda")'
          julia -e 'using Conda; Conda.add("scikit-learn")'

      - name: Configure PyCall
        run: julia -e 'ENV["PYTHON"] = ""; using Pkg; Pkg.build("PyCall")'

      - name: Run tests
        run: julia -e 'using Pkg; Pkg.activate("."); Pkg.test()'