name: CompatHelper

on:
  schedule:
    - cron: 0 0 * * *  # Runs daily at midnight UTC
  push:
    branches:
      - main  # Runs on pushes to the main branch
  workflow_dispatch:
#test
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10.0'

      - name: Add CompatHelper
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'

      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
